### ISSUE TITLE
It seems the Player QR isn't loading in the deployment.

### ISSUE THREAD

**Issue by nikhilverma360** [kleros/dappcon-game#23]
It seems the Player QR isn't loading in the deployment. We should verify whether we're using a cipher key with a length of 32 characters. This length is crucial for ensuring compatibility and functionality.

<img width="992" alt="Screenshot 2024-05-07 at 11 16 03" src="https://github.com/kleros/dappcon-game/assets/32412967/8b6eead5-5513-419b-b80c-7673db3c52b2">

**Comment by alcercu** [comment]
oh, in the env it said 256 bits

**Comment by alcercu** [comment]
going to create a PR to fix this
